export const STRINGS = {
  "app.name": "Split Stack",
  "app.description": "A competitive falling-block survival game for two players.",
  "common.back": "Back",
  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.confirm": "Confirm",
  "common.on": "On",
  "common.off": "Off",
  "common.playerFallback": "Player",
  "status.timed": "{power} · {seconds}s",
  "status.barrier": "{power} {capacity} · {seconds}s",
  "lobby.heading": "Split Stack",
  "lobby.createChallenge": "Create challenge",
  "lobby.joinChallenge": "Join challenge",
  "lobby.practice": "Practice",
  "lobby.howToPlay": "How to Play",
  "lobby.powerGlossary": "Power Glossary",
  "lobby.practiceControls": "Practice Controls",
  "lobby.settings": "Settings",
  "lobby.history": "Recent matches",
  "lobby.headToHead": "Head-to-head",
  "lobby.waitingForOpponent": "Waiting for an opponent…",
  "lobby.challengeCreated": "Challenge created. Waiting for an opponent…",
  "lobby.challengeJoined": "Challenge joined. Preparing the match…",
  "lobby.noOpenChallenge": "No open challenge is available yet.",
  "lobby.noMatches": "No competitive matches recorded yet.",
  "lobby.practiceHighScore": "Practice high score: {score}",
  "lobby.historyResult": "{players} — {outcome}",
  "lobby.tallyResult": "{players}: {score}",
  "lobby.challengeError": "The challenge update could not be saved. Try again.",
  "lobby.realtimeUnavailable":
    "Live play is unavailable here. You can still use Practice.",
  "lobby.spectatorNotice": "You are watching this challenge as a spectator.",
  "lobby.confirmingSession": "Confirming the active game session…",
  "lobby.duplicateSession":
    "This seat is controlled by a newer open Split Stack session. Watching only.",
  "match.ready": "Ready",
  "match.notReady": "Not ready",
  "match.waitingForReady": "Waiting for both players…",
  "match.countdown": "Match starts in {seconds}",
  "match.reconnecting": "Reconnecting…",
  "match.resuming": "Connection restored. Resuming in {seconds}…",
  "match.versionMismatch":
    "The players have different game versions. Update Split Stack to continue.",
  "match.desynchronization":
    "The match stopped because the game states could not be reconciled.",
  "match.webglPaused": "Display interrupted. The match is paused while WebGL recovers.",
  "match.practicePaused": "Practice paused",
  "match.practice": "Practice",
  "match.spectatorReady": "Watching Seat A and Seat B",
  "match.unsupportedWebgl":
    "This device cannot display the game board because WebGL is unavailable.",
  "match.blackoutCover": "Board concealed by Blackout",
  "match.localBoard": "Your board",
  "match.opponentBoard": "Opponent board",
  "match.seatABoard": "Seat A board",
  "match.seatBBoard": "Seat B board",
  "hud.score": "Score",
  "hud.level": "Level",
  "hud.lines": "Lines",
  "hud.hold": "Hold",
  "hud.next": "Next",
  "hud.replacementSeconds": "{power} · {seconds}s",
  "hud.replacementPieces": "{power} · {count} left",
  "hud.power": "Power",
  "hud.upcomingPower": "Upcoming power",
  "hud.incomingGarbage": "Incoming garbage",
  "hud.combo": "Combo {count}",
  "hud.backToBack": "Back-to-back",
  "hud.connected": "Connected",
  "hud.disconnected": "Disconnected",
  "hud.spectating": "Spectating",
  "controls.moveLeft": "Move left",
  "controls.moveRight": "Move right",
  "controls.softDrop": "Soft drop",
  "controls.hardDrop": "Hard drop",
  "controls.rotateClockwise": "Rotate clockwise",
  "controls.rotateCounterclockwise": "Rotate counterclockwise",
  "controls.hold": "Hold piece",
  "controls.pausePractice": "Pause practice",
  "controls.resumePractice": "Resume practice",
  "controls.pauseShort": "Pause",
  "controls.resumeShort": "Resume",
  "controls.scrambled": "Scramble is active: movement and rotation are reversed.",
  "results.victory": "Victory",
  "results.defeat": "Defeat",
  "results.draw": "Draw",
  "results.desync": "Match ended without a winner",
  "results.rematch": "Rematch",
  "results.leave": "Leave match",
  "results.leaveShort": "Leave",
  "results.duration": "Duration",
  "results.garbageSent": "Garbage sent",
  "results.tetrises": "Four-line clears",
  "results.tSpins": "T-Spins",
  "results.powersActivated": "Powers activated",
  "results.score": "Score",
  "results.lines": "Lines",
  "results.practiceOver": "Practice complete",
  "results.newHighScore": "New practice high score",
  "results.forfeit": "Opponent connection timed out",
  "settings.heading": "Settings",
  "settings.audio": "Effects audio",
  "settings.effectsVolume": "Effects volume",
  "settings.vibration": "Vibration",
  "settings.controls": "Touch controls",
  "settings.gestures": "Gestures",
  "settings.buttons": "Buttons",
  "settings.palette": "Color palette",
  "settings.colorblindPalette": "Colorblind palette",
  "settings.standardPalette": "Standard palette",
  "settings.reducedMotion": "Reduced motion",
  "settings.reducedFlashes": "Reduced flashes",
  "settings.reducedEffects": "Reduced effects and 30 FPS",
  "settings.screenShake": "Screen shake",
  "settings.gameplayTips": "Gameplay tips",
  "help.heading": "How to Play",
  "help.goal":
    "Keep your stack below the top while sending garbage and forced pieces to your opponent.",
  "help.controls":
    "Move, rotate, Hold, and drop pieces to complete horizontal lines.",
  "help.powers":
    "Line clears charge your meter. The displayed power activates automatically when the meter is full.",
  "help.specialCells":
    "A marked cell triggers only when it participates in a normal line clear.",
  "help.noAutoTutorial": "Help opens only when you choose it from the lobby.",
  "power.blackout": "Blackout",
  "power.scramble": "Scramble",
  "power.nuke": "Nuke",
  "power.barrier": "Barrier",
  "power.collapse": "Collapse",
  "power.monominoRush": "Monomino Rush",
  "power.acidRain": "Acid Rain",
  "power.blackoutDescription": "Hide your board from everyone else for 15 seconds.",
  "power.scrambleDescription":
    "Reverse your opponent’s horizontal and rotation controls for 10 seconds.",
  "power.nukeDescription":
    "Remove a guided three-by-three area from your own highest stack.",
  "power.barrierDescription": "Block up to four incoming garbage rows for 20 seconds.",
  "power.collapseDescription":
    "Compact every column downward and score any completed lines.",
  "power.monominoRushDescription": "Place one-cell pieces for eight seconds.",
  "power.acidRainDescription":
    "Use three drops that dissolve their selected columns.",
  "special.columnBomb": "Column Bomb",
  "special.garbageCore": "Garbage Core",
  "special.glitchCore": "Glitch Core",
  "help.touchRotate":
    "Tap to rotate clockwise; two-finger tap rotates counterclockwise.",
  "help.touchMove": "Drag across columns to move. Hold downward to soft drop.",
  "help.touchDrop": "Flick downward to hard drop. Swipe upward to Hold.",
  "help.keyboard":
    "Keyboard: arrows or A/D/S, Z/Q and X/E, Space, C or Shift.",
} as const;

export type StringKey = keyof typeof STRINGS;
export type StringParameters = Readonly<Record<string, string | number>>;

export function formatString(
  key: StringKey,
  parameters: StringParameters = {},
): string {
  return STRINGS[key].replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (token, name: string) => {
    const value = parameters[name];
    return value === undefined ? token : String(value);
  });
}
