export const STRINGS = {
  "app.name": "Split Stack",
  "app.description": "A competitive falling-block survival game for two players.",
  "common.back": "Back",
  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.confirm": "Confirm",
  "common.on": "On",
  "common.off": "Off",
  "common.playerFallback": "Player",
  "status.timed": "{power} · {seconds}s",
  "status.barrier": "{power} {capacity} · {seconds}s",
  "home.heading": "Split Stack",
  "home.createChallenge": "Create challenge",
  "home.cancelChallenge": "Cancel challenge",
  "home.lobby": "Lobby",
  "home.lobbyActivity": "{waiting} waiting · {live} live",
  "home.yourBest": "Your best: {score}",
  "home.chatRecord": "Chat record: {score} · {player}",
  "home.noPracticeRecord": "No Practice record yet",
  "home.practiceRecords": "Practice records",
  "home.unfinishedMatch": "Unfinished match",
  "home.unfinishedMatchSummary": "This copy can watch but cannot resume playing.",
  "home.unfinishedMatchHelpLabel": "Why can’t this copy resume the match?",
  "home.unfinishedMatchHelp":
    "Split Stack was reopened while this match was active. To prevent two copies from controlling the same player, this copy can only watch.",
  "home.gameActiveElsewhere": "The original match is still active.",
  "home.pairingActiveElsewhere": "Pairing active in another session",
  "home.pairingActiveElsewhereSummary": "This copy cannot control the pairing.",
  "home.neutralExitUnlocks": "Neutral exit unlocks in {seconds}s",
  "home.neutralExitAvailable": "Neutral exit is available.",
  "home.concedeNow": "Concede now to leave immediately.",
  "home.watchMatch": "Watch match",
  "home.concedeAndLeave": "Concede and leave",
  "home.endInterruptedMatch": "End match with no result",
  "home.endingMatch": "Ending match…",
  "home.stillWaitingForConfirmation": "Still waiting for confirmation.",
  "home.retryNow": "Retry now",
  "home.pairingDelayed": "Pairing delayed",
  "home.confirmingLong": "Still confirming the active game session…",
  "home.retryConnection": "Retry connection",
  "home.concedeConfirmationHeading": "Concede this match?",
  "home.concedeConfirmationMessage":
    "Your opponent will win, and this cannot be undone.",
  "home.concedeConfirmationAction": "Concede match",
  "home.neutralConfirmationHeading": "End match with no result?",
  "home.neutralConfirmationMessage":
    "No winner or loss will be recorded. The original game may still be open elsewhere.",
  "lobby.heading": "Split Stack",
  "lobby.browserHeading": "Lobby",
  "lobby.backHome": "Home",
  "lobby.activitySummary": "{waiting} waiting · {live} live",
  "lobby.yourActivity": "Your activity",
  "lobby.openChallenges": "Open challenges",
  "lobby.startingSoon": "Starting soon",
  "lobby.liveGames": "Live games",
  "lobby.recentResults": "Recent results",
  "lobby.standings": "Standings",
  "lobby.practiceLeaderboard": "Practice leaderboard",
  "lobby.noActivity": "No competitive activity",
  "lobby.noOpenChallenges": "No one is waiting for an opponent.",
  "lobby.noStartingSoon": "No games are starting soon.",
  "lobby.noLiveGames": "No games are live.",
  "lobby.noRecentResults": "No competitive results yet.",
  "lobby.noStandings": "No competitive standings yet.",
  "lobby.noPracticeScores": "No Practice scores recorded yet.",
  "lobby.join": "Join",
  "lobby.watch": "Watch",
  "lobby.withdraw": "Withdraw",
  "lobby.online": "Online",
  "lobby.offline": "Offline",
  "lobby.offlineJoinHint": "Creator offline · You can still join",
  "lobby.claimLost": "Another pairing was confirmed first.",
  "lobby.finishActiveMatch":
    "Finish your active match before joining another challenge.",
  "lobby.staleLink": "This link is no longer active.",
  "lobby.round": "Round {round}",
  "lobby.yourRank": "Your rank: {rank}",
  "lobby.playerColumn": "Player",
  "lobby.winsColumn": "W",
  "lobby.lossesColumn": "L",
  "lobby.drawsColumn": "D",
  "lobby.winRateColumn": "Win rate",
  "lobby.scoreColumn": "Score",
  "lobby.createChallenge": "Create challenge",
  "lobby.joinChallenge": "Join challenge",
  "lobby.practice": "Practice",
  "lobby.howToPlay": "How to Play",
  "lobby.practiceControls": "Controls",
  "lobby.settings": "Settings",
  "lobby.history": "Recent matches",
  "lobby.headToHead": "Head-to-head",
  "lobby.waitingForOpponent": "Waiting for an opponent…",
  "lobby.challengeCreated": "Challenge created. Waiting for an opponent…",
  "lobby.challengeJoined": "Challenge joined. Preparing the match…",
  "lobby.noOpenChallenge": "No open challenge is available yet.",
  "lobby.noMatches": "No competitive matches recorded yet.",
  "lobby.practiceHighScore": "Practice high score: {score}",
  "lobby.historyResult": "{players} — {outcome}",
  "lobby.tallyResult": "{players}: {score}",
  "lobby.challengeError": "The challenge update could not be saved. Try again.",
  "lobby.realtimeUnavailable":
    "Live play is unavailable here. You can still use Practice.",
  "lobby.spectatorNotice": "You are watching this challenge as a spectator.",
  "lobby.confirmingSession": "Confirming the active game session…",
  "lobby.duplicateSession":
    "This seat is bound to another game session. Watching only.",
  "match.ready": "Ready",
  "match.notReady": "Not ready",
  "match.readyUp": "Ready up",
  "match.youAreReady": "✓ You’re ready",
  "match.readyHeading": "Ready to play?",
  "match.readyHint": "Click when you’re prepared",
  "match.waitingForOpponentReady": "Waiting for opponent…",
  "match.bothPlayersReady": "Both players are ready. Starting…",
  "match.cancelReady": "Cancel readiness",
  "match.leavePairing": "Leave pairing",
  "match.withdrawPairing": "Withdraw",
  "match.youName": "{player} (You)",
  "match.waitingForPlayerReturn": "Waiting for {player} to return…",
  "match.you": "You",
  "match.opponent": "Opponent",
  "match.waitingForReady": "Waiting for both players…",
  "match.countdown": "Match starts in {seconds}",
  "match.connectionUnstable": "Connection unstable…",
  "match.connectionInterrupted": "Connection interrupted — game paused…",
  "match.reconnecting": "Reconnecting…",
  "match.reconnectDeadline":
    "Match ends in {seconds}s if your opponent does not return.",
  "match.resynchronizing": "Resynchronizing…",
  "match.resuming": "Connection restored. Resuming in {seconds}…",
  "match.versionMismatch":
    "The players have different game versions. Update Split Stack to continue.",
  "match.desynchronization":
    "The match stopped because the game states could not be reconciled.",
  "match.webglPaused": "Display interrupted. The match is paused while WebGL recovers.",
  "match.practicePaused": "Practice paused",
  "match.practice": "Practice",
  "match.menu": "Match menu",
  "match.menuPractice": "Practice is paused while this menu is open.",
  "match.menuCompetitive": "The match keeps running while this menu is open.",
  "match.returnToMatch": "Return to match",
  "match.exitWatch": "Exit watch",
  "match.waitingForLiveData": "Waiting for live game data…",
  "match.liveUpdatesInterrupted":
    "Live updates interrupted · last update {seconds}s ago",
  "match.spectatorReady": "Watching Seat A and Seat B",
  "match.unsupportedWebgl":
    "This device cannot display the game board because WebGL is unavailable.",
  "match.blackoutCover": "Board concealed by Blackout",
  "match.localBoard": "Your board",
  "match.opponentBoard": "Opponent board",
  "match.seatABoard": "Seat A board",
  "match.seatBBoard": "Seat B board",
  "hud.score": "Score",
  "hud.scoreShort": "SCR",
  "hud.level": "Level",
  "hud.levelShort": "LVL",
  "hud.lines": "Lines",
  "hud.linesShort": "LNS",
  "hud.hold": "Hold",
  "hud.next": "Next",
  "hud.replacementSeconds": "{power} · {seconds}s",
  "hud.replacementPieces": "{power} · {count} left",
  "hud.power": "Power",
  "hud.powerReady": "Power ready",
  "hud.powerReadyRetainedOne": "Power ready; 1 charge retained",
  "hud.powerReadyRetainedMany": "Power ready; {count} charges retained",
  "hud.powerCharge": "{charge} of {threshold} power charge",
  "hud.upcomingPower": "Upcoming power",
  "hud.incomingGarbage": "Incoming garbage",
  "hud.combo": "Combo {count}",
  "hud.backToBack": "Back-to-back",
  "hud.connected": "Connected",
  "hud.disconnected": "Disconnected",
  "hud.spectating": "Spectating",
  "tip.upcomingPower": "Upcoming power · {power}",
  "controls.moveLeft": "Move left",
  "controls.moveRight": "Move right",
  "controls.softDrop": "Soft drop",
  "controls.hardDrop": "Hard drop",
  "controls.rotateClockwise": "Rotate clockwise",
  "controls.rotateCounterclockwise": "Rotate counterclockwise",
  "controls.hold": "Hold piece",
  "controls.resumeShort": "Resume",
  "controls.scrambled": "Scramble is active: movement and rotation are reversed.",
  "results.victory": "Victory",
  "results.defeat": "Defeat",
  "results.draw": "Draw",
  "results.desync": "Match ended without a winner",
  "results.rematch": "Rematch",
  "results.requestRematch": "Request rematch",
  "results.acceptRematch": "Accept rematch",
  "results.rematchRequested": "Rematch requested",
  "results.newChallenge": "New challenge",
  "results.home": "Home",
  "results.practiceAgain": "Practice again",
  "results.createChallenge": "Create challenge",
  "results.leave": "Leave match",
  "results.duration": "Duration",
  "results.garbageSent": "Garbage sent",
  "results.tetrises": "Four+ line clears",
  "results.tSpins": "T-Spins",
  "results.powersActivated": "Powers activated",
  "results.score": "Score",
  "results.lines": "Lines",
  "results.practiceOver": "Practice complete",
  "results.newHighScore": "New practice high score",
  "results.forfeit": "Opponent connection timed out",
  "results.connectionLost": "Connection lost",
  "results.connectionLostHistory": "Connection lost · neutral result",
  "results.finalScores": "Final scores",
  "results.round": "Round {round}",
  "results.playerScore": "{player}: {score}",
  "results.series": "Series: {score}",
  "results.headToHead": "Head-to-head: {score}",
  "results.standingsUnchanged": "Standings unchanged.",
  "results.competitiveActions": "Competitive result actions",
  "results.practiceActions": "Practice result actions",
  "pairing.opponentFound": "Opponent found",
  "pairing.rematchReady": "Rematch ready",
  "pairing.opponentFoundMessage": "{player} joined your challenge.",
  "pairing.rematchReadyMessage": "{player} accepted the rematch.",
  "pairing.goToMatch": "Go to match",
  "pairing.cancelPairing": "Cancel pairing",
  "pairing.cancelRematch": "Cancel rematch",
  "settings.heading": "Settings",
  "settings.effects": "Effects",
  "settings.effectsVolume": "Effects volume",
  "settings.music": "Music",
  "settings.musicVolume": "Music volume",
  "settings.vibration": "Vibration",
  "settings.controls": "Touch controls",
  "settings.gestures": "Gestures",
  "settings.buttons": "Buttons",
  "settings.palette": "Color palette",
  "settings.colorblindPalette": "Colorblind palette",
  "settings.standardPalette": "Standard palette",
  "settings.reducedMotion": "Reduced motion",
  "settings.reducedFlashes": "Reduced flashes",
  "settings.graphics": "Graphics",
  "settings.graphicsAuto": "Auto",
  "settings.graphicsNormal": "Normal",
  "settings.graphicsLow": "Low",
  "settings.graphicsVeryLow": "Very Low",
  "settings.graphicsAutoStatus": "Auto currently uses {tier}.",
  "settings.screenShake": "Screen shake",
  "settings.gameplayTips": "Gameplay tips",
  "settings.copyDiagnostics": "Copy diagnostics",
  "settings.clearDiagnostics": "Clear diagnostics",
  "settings.diagnosticsReady": "Connection diagnostics",
  "settings.diagnosticsCopied": "Diagnostics copied.",
  "settings.diagnosticsCopyFailed": "Diagnostics could not be copied.",
  "settings.diagnosticsCleared": "Diagnostics cleared.",
  "help.heading": "How to Play",
  "help.goal":
    "Keep your stack below the top while sending garbage and forced pieces to your opponent.",
  "help.controls":
    "Move, rotate, Hold, and drop pieces to complete horizontal lines.",
  "help.powers":
    "Line clears charge your meter. The displayed power activates automatically when the meter is full.",
  "help.specialCells":
    "A marked cell triggers only when it participates in a normal line clear. Rotate an O piece to choose which row or column carries its mark.",
  "power.blackout": "Blackout",
  "power.scramble": "Scramble",
  "power.nuke": "Nuke",
  "power.barrier": "Barrier",
  "power.collapse": "Collapse",
  "power.monominoRush": "Monomino Rush",
  "power.acidRain": "Acid Rain",
  "power.oversize": "Oversize",
  "power.ghostJam": "Ghost Jam",
  "power.blackoutDescription": "Hide your board from everyone else for 15 seconds.",
  "power.scrambleDescription":
    "Reverse your opponent’s horizontal and rotation controls for 10 seconds.",
  "power.nukeDescription":
    "Remove a guided five-by-five area from your own highest stack.",
  "power.barrierDescription": "Block up to four incoming garbage rows for 20 seconds.",
  "power.collapseDescription":
    "Compact every column downward and score any completed lines.",
  "power.monominoRushDescription": "Place one-cell pieces for eight seconds.",
  "power.acidRainDescription":
    "Use three drops that dissolve their selected columns.",
  "power.oversizeDescription":
    "Queue one enlarged I, J, L, S, T, or Z piece for your opponent.",
  "power.ghostJamDescription":
    "Hide the target board’s ghost projection from everyone for 15 seconds.",
  "special.columnBomb": "Column Bomb",
  "special.garbageCore": "Garbage Core",
  "special.glitchCore": "Glitch Core",
  "special.blackoutDescription":
    "Conceals your board from your opponent for 15 seconds when its marked cell participates in a line clear.",
  "special.barrierDescription":
    "Blocks up to four incoming garbage rows for 20 seconds when its marked cell participates in a line clear.",
  "special.columnBombDescription":
    "Clears its entire column when its marked cell participates in a line clear.",
  "special.garbageCoreDescription":
    "Sends extra garbage when its marked cell participates in a line clear.",
  "special.glitchCoreDescription":
    "Sends your opponent a Glitch Piece. Its preview rapidly cycles through every tetromino, hiding its real shape until it spawns. Once revealed, it plays like a normal piece but cannot be held.",
  "help.touchControlsHeading": "Touch controls",
  "help.touchArea":
    "Gestures work across the entire gameplay area. Start away from a button to control the falling piece.",
  "help.gestureTap": "Tap once",
  "help.gestureTwoFingerTap": "Tap with two fingers",
  "help.gestureMove": "Drag horizontally",
  "help.gestureSoftDrop": "Drag downward and hold",
  "help.gestureHardDrop": "Flick downward",
  "help.gestureHold": "Swipe upward",
  "help.touchButtonsHeading": "On-screen buttons",
  "help.touchButtonsIntro":
    "Choose Buttons in Settings to use these controls instead of gestures.",
  "help.keyboardControlsHeading": "Keyboard controls",
  "help.actionHeading": "Action",
  "help.keysHeading": "Keys",
  "help.moveLeftRight": "Move left/right",
  "help.holdAction": "Hold",
  "help.pausePracticeAction": "Pause Practice",
  "help.meterPowersHeading": "Meter powers",
  "help.markedPowersHeading": "Marked-piece powers",
  "help.specialPiecesHeading": "Special pieces",
  "help.hollowCross": "Hollow Cross",
  "help.hollowCrossDescription":
    "A small 3×3 cardinal crimson Cross. Any normal placement that completes exactly four rows sends a Hollow Cross through the forced-piece queue. It does not rotate and can be held.",
  "help.glitchPiece": "Glitch Piece",
  "help.glitchPieceDescription":
    "Its preview rapidly cycles through every tetromino, hiding its real shape until it spawns. Once revealed, it plays like a normal piece but cannot be held.",
  "help.monomino": "Monomino",
  "help.monominoDescription":
    "A single-cell piece placed during Monomino Rush.",
  "help.oversizeShapes": "Oversize shapes",
  "help.oversizeShapesDescription":
    "Enlarged I, J, L, S, T, and Z shapes that handle normally and can be held.",
} as const;

export type StringKey = keyof typeof STRINGS;
export type StringParameters = Readonly<Record<string, string | number>>;

export function formatString(
  key: StringKey,
  parameters: StringParameters = {},
): string {
  return STRINGS[key].replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (token, name: string) => {
    const value = parameters[name];
    return value === undefined ? token : String(value);
  });
}
