export const STRINGS = {
  "app.name": "Split Stack",
  "app.description": "A competitive falling-block survival game for two players.",
  "common.back": "Back",
  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.confirm": "Confirm",
  "common.on": "On",
  "common.off": "Off",
  "common.playerFallback": "Player",
  "status.timed": "{power} · {seconds}s",
  "status.barrier": "{power} {capacity} · {seconds}s",
  "lobby.heading": "Split Stack",
  "lobby.createChallenge": "Create challenge",
  "lobby.joinChallenge": "Join challenge",
  "lobby.practice": "Practice",
  "lobby.howToPlay": "How to Play",
  "lobby.powerGlossary": "Power Glossary",
  "lobby.practiceControls": "Practice Controls",
  "lobby.settings": "Settings",
  "lobby.history": "Recent matches",
  "lobby.headToHead": "Head-to-head",
  "lobby.waitingForOpponent": "Waiting for an opponent…",
  "lobby.challengeCreated": "Challenge created. Waiting for an opponent…",
  "lobby.challengeJoined": "Challenge joined. Preparing the match…",
  "lobby.noOpenChallenge": "No open challenge is available yet.",
  "lobby.noMatches": "No competitive matches recorded yet.",
  "lobby.practiceHighScore": "Practice high score: {score}",
  "lobby.historyResult": "{players} — {outcome}",
  "lobby.tallyResult": "{players}: {score}",
  "lobby.challengeError": "The challenge update could not be saved. Try again.",
  "lobby.realtimeUnavailable":
    "Live play is unavailable here. You can still use Practice.",
  "lobby.spectatorNotice": "You are watching this challenge as a spectator.",
  "lobby.confirmingSession": "Confirming the active game session…",
  "lobby.duplicateSession":
    "This seat is controlled by a newer open Split Stack session. Watching only.",
  "match.ready": "Ready",
  "match.notReady": "Not ready",
  "match.readyUp": "Ready up",
  "match.youAreReady": "✓ You’re ready",
  "match.readyHeading": "Ready to play?",
  "match.readyHint": "Click when you’re prepared",
  "match.waitingForOpponentReady": "Waiting for opponent…",
  "match.bothPlayersReady": "Both players are ready. Starting…",
  "match.cancelReady": "Cancel readiness",
  "match.you": "You",
  "match.opponent": "Opponent",
  "match.waitingForReady": "Waiting for both players…",
  "match.countdown": "Match starts in {seconds}",
  "match.connectionUnstable": "Connection unstable…",
  "match.connectionInterrupted": "Connection interrupted — game paused…",
  "match.reconnecting": "Reconnecting…",
  "match.resynchronizing": "Resynchronizing…",
  "match.resuming": "Connection restored. Resuming in {seconds}…",
  "match.versionMismatch":
    "The players have different game versions. Update Split Stack to continue.",
  "match.desynchronization":
    "The match stopped because the game states could not be reconciled.",
  "match.webglPaused": "Display interrupted. The match is paused while WebGL recovers.",
  "match.practicePaused": "Practice paused",
  "match.practice": "Practice",
  "match.spectatorReady": "Watching Seat A and Seat B",
  "match.unsupportedWebgl":
    "This device cannot display the game board because WebGL is unavailable.",
  "match.blackoutCover": "Board concealed by Blackout",
  "match.localBoard": "Your board",
  "match.opponentBoard": "Opponent board",
  "match.seatABoard": "Seat A board",
  "match.seatBBoard": "Seat B board",
  "hud.score": "Score",
  "hud.level": "Level",
  "hud.lines": "Lines",
  "hud.hold": "Hold",
  "hud.next": "Next",
  "hud.replacementSeconds": "{power} · {seconds}s",
  "hud.replacementPieces": "{power} · {count} left",
  "hud.power": "Power",
  "hud.powerReady": "Power ready",
  "hud.powerReadyRetainedOne": "Power ready; 1 charge retained",
  "hud.powerReadyRetainedMany": "Power ready; {count} charges retained",
  "hud.powerCharge": "{charge} of {threshold} power charge",
  "hud.upcomingPower": "Upcoming power",
  "hud.incomingGarbage": "Incoming garbage",
  "hud.combo": "Combo {count}",
  "hud.backToBack": "Back-to-back",
  "hud.connected": "Connected",
  "hud.disconnected": "Disconnected",
  "hud.spectating": "Spectating",
  "controls.moveLeft": "Move left",
  "controls.moveRight": "Move right",
  "controls.softDrop": "Soft drop",
  "controls.hardDrop": "Hard drop",
  "controls.rotateClockwise": "Rotate clockwise",
  "controls.rotateCounterclockwise": "Rotate counterclockwise",
  "controls.hold": "Hold piece",
  "controls.pausePractice": "Pause practice",
  "controls.resumePractice": "Resume practice",
  "controls.pauseShort": "Pause",
  "controls.resumeShort": "Resume",
  "controls.scrambled": "Scramble is active: movement and rotation are reversed.",
  "results.victory": "Victory",
  "results.defeat": "Defeat",
  "results.draw": "Draw",
  "results.desync": "Match ended without a winner",
  "results.rematch": "Rematch",
  "results.leave": "Leave match",
  "results.leaveShort": "Leave",
  "results.duration": "Duration",
  "results.garbageSent": "Garbage sent",
  "results.tetrises": "Four-line clears",
  "results.tSpins": "T-Spins",
  "results.powersActivated": "Powers activated",
  "results.score": "Score",
  "results.lines": "Lines",
  "results.practiceOver": "Practice complete",
  "results.newHighScore": "New practice high score",
  "results.forfeit": "Opponent connection timed out",
  "results.connectionLost": "Connection lost",
  "results.connectionLostHistory": "Connection lost · neutral result",
  "settings.heading": "Settings",
  "settings.effects": "Effects",
  "settings.effectsVolume": "Effects volume",
  "settings.music": "Music",
  "settings.musicVolume": "Music volume",
  "settings.vibration": "Vibration",
  "settings.controls": "Touch controls",
  "settings.gestures": "Gestures",
  "settings.buttons": "Buttons",
  "settings.palette": "Color palette",
  "settings.colorblindPalette": "Colorblind palette",
  "settings.standardPalette": "Standard palette",
  "settings.reducedMotion": "Reduced motion",
  "settings.reducedFlashes": "Reduced flashes",
  "settings.reducedEffects": "Reduced effects and 30 FPS",
  "settings.screenShake": "Screen shake",
  "settings.gameplayTips": "Gameplay tips",
  "settings.copyDiagnostics": "Copy diagnostics",
  "settings.clearDiagnostics": "Clear diagnostics",
  "settings.diagnosticsReady": "Connection diagnostics",
  "settings.diagnosticsCopied": "Diagnostics copied.",
  "settings.diagnosticsCopyFailed": "Diagnostics could not be copied.",
  "settings.diagnosticsCleared": "Diagnostics cleared.",
  "help.heading": "How to Play",
  "help.goal":
    "Keep your stack below the top while sending garbage and forced pieces to your opponent.",
  "help.controls":
    "Move, rotate, Hold, and drop pieces to complete horizontal lines.",
  "help.powers":
    "Line clears charge your meter. The displayed power activates automatically when the meter is full.",
  "help.specialCells":
    "A marked cell triggers only when it participates in a normal line clear.",
  "help.specialCellsHeading": "Marked-piece powers",
  "help.noAutoTutorial": "Help opens only when you choose it from the lobby.",
  "power.blackout": "Blackout",
  "power.scramble": "Scramble",
  "power.nuke": "Nuke",
  "power.barrier": "Barrier",
  "power.collapse": "Collapse",
  "power.monominoRush": "Monomino Rush",
  "power.acidRain": "Acid Rain",
  "power.oversize": "Oversize",
  "power.ghostJam": "Ghost Jam",
  "power.blackoutDescription": "Hide your board from everyone else for 15 seconds.",
  "power.scrambleDescription":
    "Reverse your opponent’s horizontal and rotation controls for 10 seconds.",
  "power.nukeDescription":
    "Remove a guided five-by-five area from your own highest stack.",
  "power.barrierDescription": "Block up to four incoming garbage rows for 20 seconds.",
  "power.collapseDescription":
    "Compact every column downward and score any completed lines.",
  "power.monominoRushDescription": "Place one-cell pieces for eight seconds.",
  "power.acidRainDescription":
    "Use three drops that dissolve their selected columns.",
  "power.oversizeDescription":
    "Queue one enlarged I, J, L, S, T, or Z piece for your opponent.",
  "power.ghostJamDescription":
    "Hide the target board’s ghost projection from everyone for 15 seconds.",
  "special.columnBomb": "Column Bomb",
  "special.garbageCore": "Garbage Core",
  "special.glitchCore": "Glitch Core",
  "special.blackoutDescription":
    "Conceals your board from your opponent for 15 seconds when its marked cell participates in a line clear.",
  "special.barrierDescription":
    "Blocks up to four incoming garbage rows for 20 seconds when its marked cell participates in a line clear.",
  "special.columnBombDescription":
    "Clears its entire column when its marked cell participates in a line clear.",
  "special.garbageCoreDescription":
    "Sends extra garbage when its marked cell participates in a line clear.",
  "special.glitchCoreDescription":
    "Sends your opponent a Glitch Piece. Its preview rapidly cycles through every tetromino, hiding its real shape until it spawns. Once revealed, it plays like a normal piece but cannot be held.",
  "help.touchRotate":
    "Tap to rotate clockwise; two-finger tap rotates counterclockwise.",
  "help.touchMove": "Drag across columns to move. Hold downward to soft drop.",
  "help.touchDrop": "Flick downward to hard drop. Swipe upward to Hold.",
  "help.keyboard":
    "Keyboard: arrows or A/D/S, Z/Q and X/E, Space, C or Shift.",
  "help.touchControlsHeading": "Touch controls",
  "help.keyboardControlsHeading": "Keyboard controls",
  "help.actionHeading": "Action",
  "help.keysHeading": "Keys",
  "help.moveLeftRight": "Move left/right",
  "help.holdAction": "Hold",
  "help.pausePracticeAction": "Pause Practice",
  "help.meterPowersHeading": "Meter powers",
  "help.markedPowersHeading": "Marked-piece powers",
  "help.specialPiecesHeading": "Special pieces",
  "help.hollowCross": "Hollow Cross",
  "help.hollowCrossDescription":
    "A complete eight-cell hollow cross sent through the forced-piece queue.",
  "help.glitchPiece": "Glitch Piece",
  "help.glitchPieceDescription":
    "Its preview rapidly cycles through every tetromino, hiding its real shape until it spawns. Once revealed, it plays like a normal piece but cannot be held.",
  "help.oversizeShapes": "Oversize shapes",
  "help.oversizeShapesDescription":
    "Enlarged I, J, L, S, T, and Z shapes that handle normally and can be held.",
} as const;

export type StringKey = keyof typeof STRINGS;
export type StringParameters = Readonly<Record<string, string | number>>;

export function formatString(
  key: StringKey,
  parameters: StringParameters = {},
): string {
  return STRINGS[key].replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (token, name: string) => {
    const value = parameters[name];
    return value === undefined ? token : String(value);
  });
}
